<a href="https://colab.research.google.com/github/shichenliu97/active-matters-programmed-phase-transition/blob/main/connection_bar_tiff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2
import os


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Identify size and position of the bars

In [ ]:
path = '/content/drive/MyDrive/connection_of_bars_masks'

# size of canvas
(HB, WB) = (800, 1280) #size of the canvas

#size of the bar(s)
W1 = 300
H1 = 50
thresh = 127

# distance = distance between two bars / 2
distance = [300, 250, 200, 150, 100, 50, 25, 18] 

# Initial rectangle center matrix

R1_c = np.zeros((1, 2))
R2_c = np.zeros((1, 2))

# Initial cv2 poly matices
R1 = np.zeros((4, 2))
R2 = np.zeros((4, 2))

n = 0

for i in range(len(distance)):

  n += 1

  R1_c = np.array([WB/2 - W1/2 - distance[i], HB/2]) #center of the bar
  R2_c = np.array([WB/2 + distance[i] + W1/2, HB/2])
  
  R1 = np.array([[R1_c[0] - W1 / 2, R1_c[1] + H1/2],
               [R1_c[0] - W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] + H1/2]])
  
  R2 = np.array([[R2_c[0] - W1 / 2, R2_c[1] + H1/2],
               [R2_c[0] - W1 / 2, R2_c[1] - H1/2],
               [R2_c[0] + W1 / 2, R2_c[1] - H1/2],
               [R2_c[0] + W1 / 2, R2_c[1] + H1/2]])
  
  img = np.zeros( (HB, WB), dtype = np.uint8 )
  cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R2]), color=(255,255,255))
  im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
  filename = os.path.join(path , 'dist_bar%d.tiff' %n)
  cv2.imwrite(filename, im_bw)


im_bw

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
R1

array([[322., 425.],
       [322., 375.],
       [622., 375.],
       [622., 425.]])

## Now non-connection bars with circle in the middle

100 um radius

In [ ]:
path = '/content/drive/MyDrive/connection_of_bars_masks'

# size of canvas
(HB, WB) = (800, 1280) #size of the canvas

#size of the bar(s)
W1 = 300
H1 = 50
thresh = 127

# distance = distance between two bars / 2
distance = [300, 250, 200, 150, 100, 50, 25, 18] 

# Initial rectangle center matrix

R1_c = np.zeros((1, 2))
R2_c = np.zeros((1, 2))

# Initial cv2 poly matices
R1 = np.zeros((4, 2))
R2 = np.zeros((4, 2))

n = 0

for i in range(len(distance)):

  n += 1

  R1_c = np.array([WB/2 - W1/2 - distance[i], HB/2]) #center of the bar
  R2_c = np.array([WB/2 + distance[i] + W1/2, HB/2])
  
  R1 = np.array([[R1_c[0] - W1 / 2, R1_c[1] + H1/2],
               [R1_c[0] - W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] + H1/2]])
  
  R2 = np.array([[R2_c[0] - W1 / 2, R2_c[1] + H1/2],
               [R2_c[0] - W1 / 2, R2_c[1] - H1/2],
               [R2_c[0] + W1 / 2, R2_c[1] - H1/2],
               [R2_c[0] + W1 / 2, R2_c[1] + H1/2]])
  
  img = np.zeros( (HB, WB), dtype = np.uint8 )
  cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R2]), color=(255,255,255))
  center_coordinates = (640, 400)
  cv2.circle(img, center_coordinates, 35, color=(255,255,255), thickness=-1)
  im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
  filename = os.path.join(path , 'dist_bar%d_circle.tiff' %n)
  cv2.imwrite(filename, im_bw)


im_bw


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

##Correlation_distance_bar

In [ ]:
path = '/content/drive/MyDrive/correlation_distance'

# size of canvas
(HB, WB) = (800, 1280) #size of the canvas

#size of the bar(s)
W1 = 700
H1 = 30
thresh = 127

R1_c = np.zeros((1, 2))

# Initial cv2 poly matices
R1 = np.zeros((4, 2))
R2 = np.zeros((4, 2))

n = 0
R1_c = np.array([WB/2, HB/2])

R1 = np.array([[R1_c[0] - W1 / 2, R1_c[1] + H1/2],
               [R1_c[0] - W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] + H1/2]])

img = np.zeros( (HB, WB), dtype = np.uint8 )
cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
filename = os.path.join(path , 'correlation_long_bar.tiff')
cv2.imwrite(filename, im_bw)


True

In [ ]:
n = 0
for i in range(len(distance)):

  n += 1

  R1_c = np.array([WB/2 - W1/2 - distance[i], 3 * HB/8]) #center of the bar
  R2_c = np.array([WB/2 + distance[i] + W1/2, 3 * HB/8])
  R3_c = np.array([WB/2 - W1/2 - distance[i], 5 * HB/8]) #center of the bar
  R4_c = np.array([WB/2 + distance[i] + W1/2, 5 * HB/8])

  R1 = np.array([[R1_c[0] - W1 / 2, R1_c[1] + H1/2],
               [R1_c[0] - W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] - H1/2],
               [R1_c[0] + W1 / 2, R1_c[1] + H1/2]])
  
  R2 = np.array([[R2_c[0] - W1 / 2, R2_c[1] + H1/2],
               [R2_c[0] - W1 / 2, R2_c[1] - H1/2],
               [R2_c[0] + W1 / 2, R2_c[1] - H1/2],
               [R2_c[0] + W1 / 2, R2_c[1] + H1/2]])
  
  R3 = np.array([[R3_c[0] - W1 / 2, R3_c[1] + H1/2],
               [R3_c[0] - W1 / 2, R3_c[1] - H1/2],
               [R3_c[0] + W1 / 2, R3_c[1] - H1/2],
               [R3_c[0] + W1 / 2, R3_c[1] + H1/2]])
  
  R4 = np.array([[R4_c[0] - W1 / 2, R4_c[1] + H1/2],
               [R4_c[0] - W1 / 2, R4_c[1] - H1/2],
               [R4_c[0] + W1 / 2, R4_c[1] - H1/2],
               [R4_c[0] + W1 / 2, R4_c[1] + H1/2]])
  
  img = np.zeros( (HB, WB), dtype = np.uint8 )
  cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R2]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R3]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R4]), color=(255,255,255))
  im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
  filename = os.path.join(path , 'dist_bar_2_%d.tiff' %n)
  cv2.imwrite(filename, im_bw)


im_bw

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:

R1 = np.array([[800, 720],
               [800, 560],
               [960, 560],
               [960, 720]])

R2 = np.array([[800, 560],
               [800, 400],
               [960, 400],
               [960, 560]])

R3 = np.array([[640, 560],
               [640, 400],
               [800, 400],
               [800, 560]])

R4 = np.array([[800, 400],
               [800, 240],
               [960, 240],
               [960, 400]])

R5 = np.array([[480, 400],
               [480, 240],
               [640, 240],
               [640, 400]])

R6 = np.array([[320, 240],
               [320, 80],
               [960, 80],
               [960, 240]])

img = np.zeros( (HB, WB), dtype = np.uint8 )
cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
cv2.fillPoly(img, np.int32([R2]), color=(255,255,255))
cv2.fillPoly(img, np.int32([R3]), color=(255,255,255))
cv2.fillPoly(img, np.int32([R4]), color=(255,255,255))
cv2.fillPoly(img, np.int32([R5]), color=(255,255,255))
cv2.fillPoly(img, np.int32([R6]), color=(255,255,255))
im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
cv2.imwrite('image.tiff', im_bw)

R1

array([[800, 720],
       [800, 560],
       [960, 560],
       [960, 720]])

In [ ]:
z = cv2.fillPoly(img, np.int32([R6]), color=(255,255,255))

In [ ]:
z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
#size of the bar(s)
W2 = 150
H2 = 25
thresh = 127

distance_1 = [12.5, 40]

In [ ]:
n = 0
for i in range(len(distance_1)):

  n += 1

  R1_c = np.array([410 - distance_1[i] - H2/2, 140 + H2/2]) #center of the bar
  R2_c = np.array([WB/2 - 20 - W2/2, 140 + H2/2])
  R3_c = np.array([WB/2 + 20 + W2/2, 140 + H2/2]) #center of the bar
  R4_c = np.array([WB/2 + 20 + W2 + distance_1[i] + W2/2, 140 + H2/2])
  R5_c = np.array([410 - distance_1[i] - H2/2, 140 + H2/2 + 140 + H2/2]) #center of the bar
  R6_c = np.array([WB/2 - 20 - W2/2, 140 + H2/2 + 140 + H2/2])
  R7_c = np.array([WB/2 + 20 + W2/2, 140 + H2/2 + 140 + H2/2]) #center of the bar
  R8_c = np.array([WB/2 + 20 + W2 + distance_1[i] + W2/2, 140 + H2/2 + 140 + H2/2])
  R9_c = np.array([410 - distance_1[i] - H2/2, 140 + H2/2 + 280 + H2]) #center of the bar
  R10_c = np.array([WB/2 - 20 - W2/2, 140 + H2/2 + 280 + H2])
  R11_c = np.array([WB/2 + 20 + W2/2, 140 + H2/2 + 280 + H2]) #center of the bar
  R12_c = np.array([WB/2 + 20 + W2 + distance_1[i] + W2/2, 140 + H2/2 + 280 + H2])
  R13_c = np.array([410 - distance_1[i] - H2/2, 140 + H2/2 + 420 + 3 * H2 / 2]) #center of the bar
  R14_c = np.array([WB/2 - 20 - W2/2, 140 + H2/2 + 420 + 3 * H2 / 2])
  R15_c = np.array([WB/2 + 20 + W2/2, 140 + H2/2 + 420 + 3 * H2 / 2]) #center of the bar
  R16_c = np.array([WB/2 + 20 + W2 + distance_1[i] + W2/2, 140 + H2/2 + 420 + 3 * H2 / 2])

  R1 = np.array([[R1_c[0] - W2 / 2, R1_c[1] + H2/2],
               [R1_c[0] - W2 / 2, R1_c[1] - H2/2],
               [R1_c[0] + W2 / 2, R1_c[1] - H2/2],
               [R1_c[0] + W2 / 2, R1_c[1] + H2/2]])
  
  R2 = np.array([[R2_c[0] - W2 / 2, R2_c[1] + H2/2],
               [R2_c[0] - W2 / 2, R2_c[1] - H2/2],
               [R2_c[0] + W2 / 2, R2_c[1] - H2/2],
               [R2_c[0] + W2 / 2, R2_c[1] + H2/2]])
  
  R3 = np.array([[R3_c[0] - W2 / 2, R3_c[1] + H2/2],
               [R3_c[0] - W2 / 2, R3_c[1] - H2/2],
               [R3_c[0] + W2 / 2, R3_c[1] - H2/2],
               [R3_c[0] + W2 / 2, R3_c[1] + H2/2]])
  
  R4 = np.array([[R4_c[0] - W2 / 2, R4_c[1] + H2/2],
               [R4_c[0] - W2 / 2, R4_c[1] - H2/2],
               [R4_c[0] + W2 / 2, R4_c[1] - H2/2],
               [R4_c[0] + W2 / 2, R4_c[1] + H2/2]])
  
  R5 = np.array([[R5_c[0] - W2 / 2, R5_c[1] + H2/2],
               [R5_c[0] - W2 / 2, R5_c[1] - H2/2],
               [R5_c[0] + W2 / 2, R5_c[1] - H2/2],
               [R5_c[0] + W2 / 2, R5_c[1] + H2/2]])
  
  R6 = np.array([[R6_c[0] - W2 / 2, R6_c[1] + H2/2],
               [R6_c[0] - W2 / 2, R6_c[1] - H2/2],
               [R6_c[0] + W2 / 2, R6_c[1] - H2/2],
               [R6_c[0] + W2 / 2, R6_c[1] + H2/2]])
  
  R7 = np.array([[R7_c[0] - W2 / 2, R7_c[1] + H2/2],
               [R7_c[0] - W2 / 2, R7_c[1] - H2/2],
               [R7_c[0] + W2 / 2, R7_c[1] - H2/2],
               [R7_c[0] + W2 / 2, R7_c[1] + H2/2]])
  
  R8 = np.array([[R8_c[0] - W2 / 2, R8_c[1] + H2/2],
               [R8_c[0] - W2 / 2, R8_c[1] - H2/2],
               [R8_c[0] + W2 / 2, R8_c[1] - H2/2],
               [R8_c[0] + W2 / 2, R8_c[1] + H2/2]])

  R9 = np.array([[R9_c[0] - W2 / 2, R9_c[1] + H2/2],
               [R9_c[0] - W2 / 2, R9_c[1] - H2/2],
               [R9_c[0] + W2 / 2, R9_c[1] - H2/2],
               [R9_c[0] + W2 / 2, R9_c[1] + H2/2]])
  
  R10 = np.array([[R10_c[0] - W2 / 2, R10_c[1] + H2/2],
               [R10_c[0] - W2 / 2, R10_c[1] - H2/2],
               [R10_c[0] + W2 / 2, R10_c[1] - H2/2],
               [R10_c[0] + W2 / 2, R10_c[1] + H2/2]])
  
  R11 = np.array([[R11_c[0] - W2 / 2, R11_c[1] + H2/2],
               [R11_c[0] - W2 / 2, R11_c[1] - H2/2],
               [R11_c[0] + W2 / 2, R11_c[1] - H2/2],
               [R11_c[0] + W2 / 2, R11_c[1] + H2/2]])
  
  R12 = np.array([[R12_c[0] - W2 / 2, R12_c[1] + H2/2],
               [R12_c[0] - W2 / 2, R12_c[1] - H2/2],
               [R12_c[0] + W2 / 2, R12_c[1] - H2/2],
               [R12_c[0] + W2 / 2, R12_c[1] + H2/2]])
  
  R13 = np.array([[R13_c[0] - W2 / 2, R13_c[1] + H2/2],
               [R13_c[0] - W2 / 2, R13_c[1] - H2/2],
               [R13_c[0] + W2 / 2, R13_c[1] - H2/2],
               [R13_c[0] + W2 / 2, R13_c[1] + H2/2]])
  
  R14 = np.array([[R14_c[0] - W2 / 2, R14_c[1] + H2/2],
               [R14_c[0] - W2 / 2, R14_c[1] - H2/2],
               [R14_c[0] + W2 / 2, R14_c[1] - H2/2],
               [R14_c[0] + W2 / 2, R14_c[1] + H2/2]])
  
  R15 = np.array([[R15_c[0] - W2 / 2, R15_c[1] + H2/2],
               [R15_c[0] - W2 / 2, R15_c[1] - H2/2],
               [R15_c[0] + W2 / 2, R15_c[1] - H2/2],
               [R15_c[0] + W2 / 2, R15_c[1] + H2/2]])
  
  R16 = np.array([[R16_c[0] - W2 / 2, R16_c[1] + H2/2],
               [R16_c[0] - W2 / 2, R16_c[1] - H2/2],
               [R16_c[0] + W2 / 2, R16_c[1] - H2/2],
               [R16_c[0] + W2 / 2, R16_c[1] + H2/2]])
  
  img = np.zeros( (HB, WB), dtype = np.uint8 )
  cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R2]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R3]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R4]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R5]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R6]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R7]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R8]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R9]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R10]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R11]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R12]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R13]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R14]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R15]), color=(255,255,255))
  cv2.fillPoly(img, np.int32([R16]), color=(255,255,255))
  im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
  filename = os.path.join(path , 'lattice_bar_2_%d.tiff' %n)
  cv2.imwrite(filename, im_bw)


im_bw

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
import numpy as np
import cv2
import math

path = '/content/drive/MyDrive/connection_of_bars_masks/fig_4/static_rotation/1'


##one rotating bar
(HB, WB) = (800, 1280) #size of the canvas


thresh = 127
num_pix = 360
num_bar = 4
W1 = 225
H1 = 36

W2 = 135
H2 = 27

#Rectangle
P0 = np.array([1.3*WB/4, HB/4]) #center of the bar

P1 = np.array([1.3*WB/4, 3 * HB/4]) #center of the bar

C = np.array([W1,H1]) #width, height of the bar
ang_rot = 2 #degrees of rotation in each frame
ang = 0 #initial angle



class RRect_center:
  def __init__(self, p0, s, ang):
    (self.W, self.H) = s # rectangle width and height
    self.d = math.sqrt(self.W**2 + self.H**2)/2.0 # distance from center to vertices
    #self.c = (int(p0[0]+self.W/2.0),int(p0[1]+self.H/2.0)) # center point coordinates
    self.c = p0.astype(int) # center point coordinates
    self.ang = ang # rotation angle
    self.alpha = math.radians(self.ang) # rotation angle in radians
    self.beta = math.atan2(self.H, self.W) # angle between d and horizontal axis
    # Center Rotated vertices in image frame
    self.P0 = (int(self.c[0] - self.d * math.cos(self.beta - self.alpha)), int(self.c[1] - self.d * math.sin(self.beta-self.alpha)))
    self.P1 = (int(self.c[0] - self.d * math.cos(self.beta + self.alpha)), int(self.c[1] + self.d * math.sin(self.beta+self.alpha)))
    self.P2 = (int(self.c[0] + self.d * math.cos(self.beta - self.alpha)), int(self.c[1] + self.d * math.sin(self.beta-self.alpha)))
    self.P3 = (int(self.c[0] + self.d * math.cos(self.beta + self.alpha)), int(self.c[1] - self.d * math.sin(self.beta+self.alpha)))

    self.verts = np.array([[self.P0,self.P1,self.P2,self.P3]], dtype=np.int32)
    
for nn in range(num_pix):
    nn += 1
    img = np.zeros( (HB, WB) ) # create a single channel 1280x800 pixel black image
   
    rr0 = RRect_center(P0,C,ang)
    rr1 = RRect_center(P1,C,ang)

    cv2.fillPoly(img, rr0.verts, color=(255,255,255))
    cv2.fillPoly(img, rr1.verts, color=(255,255,255))

    R1_c = np.array([700, HB/4]) #center of the bar
    R2_c = np.array([700, HB/2])
    R3_c = np.array([700, 3 * HB / 4]) #center of the bar
    R4_c = np.array([920, HB/4]) #center of the bar
    R5_c = np.array([920, HB/2])
    R6_c = np.array([920, 3 * HB / 4]) #center of the bar
    
    R1 = np.array([[R1_c[0] - W2 / 2, R1_c[1] + H2/2],
               [R1_c[0] - W2 / 2, R1_c[1] - H2/2],
               [R1_c[0] + W2 / 2, R1_c[1] - H2/2],
               [R1_c[0] + W2 / 2, R1_c[1] + H2/2]])
  
    R2 = np.array([[R2_c[0] - W2 / 2, R2_c[1] + H2/2],
               [R2_c[0] - W2 / 2, R2_c[1] - H2/2],
               [R2_c[0] + W2 / 2, R2_c[1] - H2/2],
               [R2_c[0] + W2 / 2, R2_c[1] + H2/2]])
  
    R3 = np.array([[R3_c[0] - W2 / 2, R3_c[1] + H2/2],
               [R3_c[0] - W2 / 2, R3_c[1] - H2/2],
               [R3_c[0] + W2 / 2, R3_c[1] - H2/2],
               [R3_c[0] + W2 / 2, R3_c[1] + H2/2]])
  
    R4 = np.array([[R4_c[0] - W2 / 2, R4_c[1] + H2/2],
               [R4_c[0] - W2 / 2, R4_c[1] - H2/2],
               [R4_c[0] + W2 / 2, R4_c[1] - H2/2],
               [R4_c[0] + W2 / 2, R4_c[1] + H2/2]])
  
    R5 = np.array([[R5_c[0] - W2 / 2, R5_c[1] + H2/2],
               [R5_c[0] - W2 / 2, R5_c[1] - H2/2],
               [R5_c[0] + W2 / 2, R5_c[1] - H2/2],
               [R5_c[0] + W2 / 2, R5_c[1] + H2/2]])
  
    R6 = np.array([[R6_c[0] - W2 / 2, R6_c[1] + H2/2],
               [R6_c[0] - W2 / 2, R6_c[1] - H2/2],
               [R6_c[0] + W2 / 2, R6_c[1] - H2/2],
               [R6_c[0] + W2 / 2, R6_c[1] + H2/2]])
    
    ang += ang_rot

    cv2.fillPoly(img, np.int32([R1]), color=(255,255,255))
    cv2.fillPoly(img, np.int32([R2]), color=(255,255,255))
    cv2.fillPoly(img, np.int32([R3]), color=(255,255,255))
    cv2.fillPoly(img, np.int32([R4]), color=(255,255,255))
    cv2.fillPoly(img, np.int32([R5]), color=(255,255,255))
    cv2.fillPoly(img, np.int32([R6]), color=(255,255,255))
    im_bw = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
    filename = os.path.join(path , 'rotbar%d.png' %nn)

    
    cv2.imwrite(filename, im_bw)